TourWebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('tour.urls'))
]
urlpatterns += path('ckeditor/', include('ckeditor_uploader.urls')),
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from core.views import index

urlpatterns = [
    path('', index, name='index'),
]

tour/urls.py
from django.urls import path

from tour.views import *

urlpatterns = [
    path('tours/<int:id>/', country_detail, name='country_detail'),
    path('tour_detail/<int:id>/', tour_detail, name='tour_detail')
]

core/models.py
from django.db import models


class Logo(models.Model):
    text = models.TextField()
    image = models.ImageField(upload_to='logo/images')

    def __str__(self):
        return f'{self.image.url}'

    class Meta:
        verbose_name = 'Loqo'
        verbose_name_plural = 'Loqo'


class Slider(models.Model):
    image = models.ImageField(upload_to='sliders/images/')

    def __str__(self):
        return f'{self.image.url}'

    class Meta:
        verbose_name = 'Slayder'
        verbose_name_plural = 'Slayderlər'


class ContactInfo(models.Model):
    phone = models.CharField(max_length=100, verbose_name="Əlaqə Nömrəsi")
    email = models.EmailField()
    address = models.CharField(max_length=100, verbose_name="Ünvan")

    def __str__(self):
        return f'Phone : {self.phone} ----  Email : {self.email}'

    class Meta:
        verbose_name = 'Əlaqə məlumatı'
        verbose_name_plural = 'Əlaqə məlumatları'


class SocialMedia(models.Model):
    media_types = (
        ('whatsapp', 'Whatsapp'),
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    )
    media = models.CharField(unique=True, max_length=50, choices=media_types)
    url = models.URLField()

    def __str__(self):
        return f'Media : {self.media}'

    class Meta:
        verbose_name = 'Sosial Şəbəkə'
        verbose_name_plural = 'Sosial Şəbəkələr'


class Service(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    button_text = models.CharField(max_length=50)
    button_url = models.URLField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Xidmət Tərkibi'
        verbose_name_plural = 'Xidmət Tərkibi'


class InfoBlock(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()

    def __str__(self):
        return self.title

tour/models.py
from ckeditor_uploader.fields import RichTextUploadingField

from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=55)
    number = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ölkə'
        verbose_name_plural = 'Ölkələr'
        ordering = ('number',)


class Day(models.Model):
    name = models.CharField(max_length=55)
    number = models.PositiveIntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Gün'
        verbose_name_plural = 'Günlər'
        ordering = ('number',)


class Tour(models.Model):
    days = models.ManyToManyField(Day, verbose_name='Günlər')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name='Ölkə')
    show_popular = models.BooleanField(default=False, verbose_name='Tüm turlarda göstər')
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='tour/images')
    price = models.CharField(max_length=20)
    content = RichTextUploadingField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Tur'
        verbose_name_plural = 'Turlar'


class TourImage(models.Model):
    image = models.ImageField(upload_to='Tour/images')
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = 'Tur Şəkil '
        verbose_name_plural = 'Tur Şəkiləri'


class Reservation(models.Model):
    user = models.CharField(max_length=100, verbose_name="Ad,Soyad")
    email = models.EmailField()
    phone = models.CharField(max_length=100, verbose_name="Telefon Nömrəsi")
    date = models.DateField(verbose_name="Tur Tarixi")
    adult = models.CharField(max_length=100, verbose_name="Böyük")
    child = models.CharField(max_length=100, verbose_name="Uşaq 2-12")
    baby = models.CharField(max_length=100, verbose_name="Uşaq 0-2")
    name_tour = models.ForeignKey(Tour, on_delete=models.CASCADE, blank=True, null=False)

    def __str__(self):
        return self.user

    class Meta:
        verbose_name = 'Sifariş'
        verbose_name_plural = 'Sifarişler'

tour/forms.py
from django import forms

from tour.models import Reservation


class ApplyForm(forms.ModelForm):

    adult = forms.ChoiceField(widget=forms.Select(attrs={
        'class': 'form-control',

    }),
        choices=(
            [('1', '1'),
             ('2', '2'),
             ('3', '3'),
             ('4', '4'), ]
        ), required=True, )

    child = forms.ChoiceField(widget=forms.Select(attrs={
        'class': 'form-control',

    }),
        choices=(
            [('1', 'Çocuk Yok'),
             ('2', '1'),
             ('3', '2'),
             ('4', '3'), ]
        ), required=True, )

    baby = forms.ChoiceField(widget=forms.Select(attrs={
        'class': 'form-control',

    }),
        choices=(
            [('1', 'Çocuk Yok'),
             ('2', '1'),
             ('3', '2'),
             ('4', '3'), ]
        ), required=True, )

    class Meta:
        model = Reservation
        fields = ['user', 'email', 'phone', 'date', 'adult', 'child', 'baby']

        widgets = {
            'user': forms.TextInput(attrs={
                'class': 'form-control '
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control ',
            }),
            'phone': forms.TextInput(attrs={
                'class': 'form-control ',

            }),

            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={'class': 'form-control',
                       'type': 'date',
                       }),

        }

core/views.py
from django.shortcuts import render
from core.models import Slider, Service, InfoBlock
from tour.models import Tour


def index(request):
    context = {
        'sliders': Slider.objects.all(),
        'sow_tur': Tour.objects.filter(show_popular=True).all(),
        'service': Service.objects.last(),
        'info_block': InfoBlock.objects.all()[:3]

    }

    return render(request, 'index.html', context)

tour/views.py
from django.shortcuts import render
from tour.models import *
from tour.forms import ApplyForm


def tour_detail(request, id):
    tour = Tour.objects.filter(id=id).last(),
    for obj in tour:
        print(obj.title)
    error = ''
    if request.method == 'POST':
        form = ApplyForm(request.POST)
        if form.is_valid():
            reservation = form.save()

            if form.is_valid():
                reservation = form.save()
                tour = Tour.objects.get(id=int(id))
                reservation.name_tour = tour
                reservation.save()


        else:
            error = 'Məlumat səhv daxil edilib!'
    form = ApplyForm()
    context = {
        "info": Reservation.objects.last(),
        "tour_inside": Tour.objects.filter(id=id).last(),
        "rest": Tour.objects.all()[:4],
        'form': form,
        'error': error,

    }
    return render(request, 'tour_detail.html', context)


def country_detail(request, id):
    country = Country.objects.filter(id=id).last()
    tours = Tour.objects.filter(country=country).all()

    context = {
        "tours": tours,
        "country": country,

    }
    return render(request, 'tours.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <!-- FONT-AWESOME  -->
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- SWIPER JS -->
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="/static/css/main.css">
    <title>Document</title>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img class="logo" src="{{ logo.image.url }}" alt="">
            </a>

            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target=".navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <div id="navbar-collapse" class="navbar-collapse justify-content-end collapse">
                <ul class="nav navbar-nav align-items-lg-center">
                    {% for country in countries %}
                        <li class="nav-item">
                            <a href="{% url 'country_detail' country.id %}"
                               class="nav-link active">{{ country.name }}</a></li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}
<a href="{{ media_whatsapp.url }}" class="float" target="_blank">
    <i class="fab fa-whatsapp"></i>
</a>
<footer>
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-lg-4 col-md-6 col-sm-8">
                <div class="footer-about">
                    <a class="navbar-brand" href="{% url 'index' %}"><img class="logo" src="{{ logo.image.url }}"
                                                                          alt=""></a>
                    <p>{{ logo.text }}</p>
                    <div class="footer-social">
                        {% for social in media %}
                            <a href="{{ social.url }}"><i class="fab fa-{{ social.media }}-square"></i></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-6 mt-4 mt-sm-5 mt-md-0">
                <div class="footer-nav">
                    <h4 class="footer-header">TURLAR</h4>
                    <ul>
                        {% for country in countries %}
                            <li><a href="{% url 'country_detail' country.id %}"> {{ country.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-8 col-sm-6 mt-4 mt-sm-5 mt-lg-0">
                <div class="footer-services">
                    <h4 class="footer-header">Services</h4>
                    <ul>
                        <li><a href="#">Blackforest</a></li>
                        <li><a href="#">Bodhubon</a></li>
                        <li><a href="#">Rongdhonu</a></li>
                        <li><a href="#">Meghrong</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-8  mt-4 mt-sm-5 mt-lg-0">
                <div class="footer-contact">
                    <h4 class="footer-header">Contact Us</h4>
                    <a href="">
                        <i class="fas fa-map-marker-alt"></i>
                        {{ contact_info.address }}
                    </a>
                    <a href="">
                        <i class="fas fa-envelope"></i>
                        {{ contact_info.email }}</a>
                    <a href="">
                        <i class="fas fa-phone-alt"></i>
                        {{ contact_info.phone }}</a>
                </div>
            </div>
        </div>
    </div>
</footer>

<!--SWIPPER -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<!-- BOOTSTRAP -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>
<!-- CUSTOM -->
<script src="/static/js/custom.js"></script>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aqrobiocore.az</title>
</head>
<body style="background-color: black;">
    <H1 style="color: brown; align-items: center; justify-content: center;">Coming soon</H1>
</body>
</html>

templates/tour_detail.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <section id="product-detail">
            <div class="container">
                <div class="row">
                    <div class="col-7">
                        <div class="product-details-title">{{ tour_inside.title }}</div>
                        <div class="product-price">{{ tour_inside.price }}</div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-7">
                        <div class="product-detail-left">
                            <div class="swiper mySwiper2">
                                <div class="swiper-wrapper">
                                    {% for img in tour_inside.tourimage_set.all %}
                                        <div class="swiper-slide">
                                            <img src="{{ img.image.url }}"
                                                 alt="">
                                        </div>
                                    {% endfor %}

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-5 mt-4 mt-lg-0">
                        <div class="product-detail-right">
                            <div class="product-details">
                                <div class="product-options">
                                    <form method="post">
                                        {% csrf_token %}

                                        <div class="form-group  product-option-select">
                                            <label name="user" class="control-label" for="name">Ad, Soyad</label>
                                            {{ form.user }}
                                        </div>

                                        <div class="form-group  product-option-select">
                                            <label name="email" class="control-label" for="email">Email</label>
                                            {{ form.email }}
                                        </div>
                                        <div class="form-group  product-option-select">
                                            <label name="phone" class="control-label" for="number">Telefon
                                                nömmrəsi</label>
                                            {{ form.phone }}
                                        </div>

                                        <div class="form-group product-option-date">
                                            <label name="date" class="control-label" for="date">Tur Tarihi</label>
                                            {{ form.date }}                                        </div>

                                        <div class="form-group  product-option-select">
                                            <label name="adult" class="control-label" for="adult">Yetişkin</label>
                                            {{ form.adult }}
                                        </div>

                                        <div class="form-group  product-option-select">
                                            <label name="child" class="control-label" for="older-child">Çocuk
                                                2-12</label>
                                            {{ form.child }}
                                        </div>

                                        <div class="form-group  product-option-select">
                                            <label name="baby" class="control-label" for="little-child">Çocuk
                                                0-2</label>
                                            {{ form.baby }}
                                        </div>
                                        <button type="submit" class="booking-btn">Hızlı Rezervasyon</button>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row justify-content-end">
                    <div class="col-lg-5 col-12">
                        <div class="contact-box mt-3">
                            <p class="contact-caption">
                                İstəyirsinizsə, telefonla sifarişinizi tamamlaya bilərsiniz. </p>
                            <a class="call-btn" href="tel:{{ contact_info.phone }}">
                                <i class="fas fa-headset"></i>
                                {{ contact_info.phone }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="check-editor">
            <div class="container">
                <div class="col-12">

                    <h2>Ətraflı məlumat:</h2>
                    <div>
                        {{ tour_inside.content|safe }}

                    </div>
                </div>
            </div>


        </section>

        <section id="tour-list">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="all-tours">
                            <h2>
                                ŞUNLARI DA BEĞENEBİLİRSİNİZ</h2>
                        </div>
                    </div>
                </div>
                <div class="row g-3">
                    {% for blog in rest %}
                        <div class="col-lg-3 col-md-4 col-sm-6 text-center">
                            <a href="" class="tour-box">
                                <div class="tour-img">
                                    <img src="{{ blog.image.url }}"
                                         alt="">
                                </div>
                                <div class="caption">
                                    <h3 class="tour-name">
                                        {{ blog.title }}
                                    </h3>
                                    <div class="tour-footer">
                                        <div class="tour-date">
                                            <i class="fas fa-calendar-alt"></i>
                                            O Sa Cu
                                        </div>
                                        <div class="tour-price">
                                            {{ blog.price }}
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>

        </section>
    </main>
{% endblock %}

templates/tours.html
{% extends 'base.html' %}
{% block content %}
    <main>
        <section id="tour-list">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="all-tours">
                            <h2>
                                {{ country.name }}
                            </h2>
                        </div>
                    </div>
                </div>
                <div class="row g-3">
                    {% for b in tours %}
                        <div class="col-lg-3 col-md-4 col-sm-6 text-center">
                            <a href="{% url 'tour_detail' b.id %}" class="tour-box">
                                <div class="tour-img">
                                    <img src="{{ b.image.url }}"
                                         alt="">
                                </div>
                                <div class="caption">
                                    <h3 class="tour-name">{{ b.title }}</h3>
                                    <div class="tour-footer">
                                        <div class="tour-date">

                                            <i class="fas fa-calendar-alt"></i>
                                            {% for tour in tours %}
                                                {% for day in tour.days.all %}
                                                    {{ day.name }}
                                                {% endfor %}
                                            {% endfor %}

                                        </div>
                                        <div class="tour-price">{{ b.price }}</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>

        </section>
    </main>
{% endblock %}